### ISSUE TITLE
Searching repositories by topic

### ISSUE THREAD

**Issue by jugaltheshah** [NerdWalletOSS/shepherd#352]
Hi folks,

I'm having an issue searching for repositories matching a topic while trying to create a migration.

For example, I created the following shepherd.yml:
```
id: 2021-01-04-test-topic-search
title: |
  chore: test topic searching
adapter:
  type: github
  search_query: org:my-org-name topic:my-topic
hooks:
  apply: echo $SHEPHERD_MIGRATION_DIR
```
I then ran `shepherd checkout .` in the migration folder. This comes up with 0 repositories:
```
$ shepherd checkout .
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
✔ Loaded 0 repos

Checked out 0 out of 0 repos
```
If I take the exact same `search_query` and search for it on Github.com, it comes up with the correct number of repos (changing the org & topic, of course).

Any ideas what the issue could be? 

P.S. For `GITHUB_TOKEN`, I used a token with which I was able to update topics, so I assume it should be able to read/search for topics also.
