### ISSUE TITLE
Sed commands replace branch names

### ISSUE THREAD

**Issue by DougCal** [NerdWalletOSS/shepherd#569]
Hi everyone.  Thanks so much for having this library!  I was running this today and ran into a weird issue.  I ran a sed command recursively through a repo, and noticed that it also replaces the branch name that is going to push when I run `shepherd push [my-migration]`, and results in 422s when I run `shephered pr [my-migration]` due to the branch name being missing upstream.

In the example, I would expect the branch name `john_c/replace_DirectCarrier_with_IntegratedCarrier`, but I instead pushed up `john_c/replace_IntegratedCarrier_with_IntegratedCarrier`.  I worked around it just by simply changing the branch name to something that doesn't say "DirectCarrier".

```yml
id: john_c/replace_DirectCarrier_with_IntegratedCarrier
title: Replace DirectCarrier with IntegratedCarrier
adapter:
  type: github
  search_type: code
  search_query: org:mothership "DirectCarrier"
hooks:
  should_migrate:
    - ls package.json
    - ls yarn.lock
    - grep "[redacted]" package.json
  post_checkout:
    - yarn
  apply:
    - find . -type f -exec sed -i '' -e 's/DirectCarrier/IntegratedCarrier/g' {} +
  pr_message: echo "Replace 'DirectCarrier' with 'IntegratedCarrier'"
```

Much appreciated!
