### ISSUE TITLE
Github auth error (?)

### ISSUE THREAD

**Issue by alexturek** [NerdWalletOSS/shepherd#77]
# Problem

When first trying to run `shepherd`, I'm getting an error related to `login()` that I suspect is due to lack of Github auth credentials.

This is version `1.2.0` (current latest) on node `10.15.0`

```
shepherd checkout temp
```
```
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
TypeError: Cannot read property 'login' of undefined
    at new GithubAdapter (/Users/aturek/try-shepherd/node_modules/@nerdwallet/shepherd/lib/adapters/github.js:55:59)
    at Object.adapterForName (/Users/aturek/try-shepherd/node_modules/@nerdwallet/shepherd/lib/adapters/index.js:10:20)
    at Object.<anonymous> (/Users/aturek/try-shepherd/node_modules/@nerdwallet/shepherd/lib/cli.js:61:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/aturek/try-shepherd/node_modules/@nerdwallet/shepherd/lib/cli.js:5:58)
    
```

# Repro steps

1. `yarn add @nerdwallet/shepherd`
2. `mkdir temp`
3. write this into `temp/shepherd.yml` (sample YAML file from [the blog post](https://www.nerdwallet.com/blog/engineering/shepherd-automating-code-changes/))

    ```yaml
    id: 2018.07.16-eslintrc-yml
    title: Rename all .eslintrc files to .eslintrc.yml
    adapter:
      type: github
      search_query: org:NerdWallet path:/ filename:.eslintrc
    hooks:
      should_migrate:
        - ls .eslintrc
        - git log -1 --format=%cd | grep 2018 --silent
      apply: mv .eslintrc .eslintrc.yml
      pr_message: echo "Hey! This PR renames `.eslintrc` to `.eslintrc.yml`" 
    ```
4. `shepherd checkout temp`
